ITabCompleterBuilder
TriggerReactor/TriggerReactor pull request #373
Opened 2021-04-18 14:58 UTC by rkdrns4747

2021-04-18 15:01 UTC, rkdrns4747 commented
Fixing errors.

2021-04-18 15:22 UTC, rkdrns4747 commented
@wysohn 
Want you to check 4fc87e7 push when reviewing this. I implemented the removed code with builder logic, still cannot guarantee they are in same logic.

2021-04-19 01:21 UTC, wysohn commented
@rkdrns4747 
Hey, this looks really good! thank you for the hard work.

I am getting some heavy load from schoolwork, so I will be checking on it as soon as possible.

Just looking at a glance, just as a suggestion, wouldn't it be looking better to use a static method to create a new builder instance than using the `new` keyword?

For example, making the constructor `private`, and create a public static function that merely calls the private constructor which can't be accessed directly outside the scope of the class.

```
(new Builder("abc"))
    .a()
    .b()   
    .builder()
```
or
```
Builder.for("abc")
    .a()
    .b()   
    .builder()
```
 I will leave it up to you

---

Also `ITabCompleterBuilder` sounds a bit awkward since the `I` in front suggests that it's an interface, so how about naming it `TabCompleterBuilder` instead?

2021-04-19 05:52 UTC, rkdrns4747 commented
@wysohn gotcha.

2021-06-20 03:54 UTC, wysohn requested changes
Rofl I just realized that I didn't 'submit' the review

no wonder why you didn't respond :0

Sorry can you take a look at it these? Thanks!

2021-06-23 06:20 UTC, wysohn commented
@rkdrns4747 
If I don't get any response by this week, I will push it to the next release

2021-06-23 06:32 UTC, rkdrns4747 commented
I'll fix it on sunday. Already checked your comment, but there's still no time to sit in front of monitor😔

2021-07-02 07:30 UTC, wysohn commented
@rkdrns4747 
Any updates yet?

2021-07-02 07:34 UTC, rkdrns4747 commented
looks like we have to use it without fixing these things for this moment. Let's push it on development, and fix the issues later when I can finally use keyboard (´ー｀)

2021-07-02 07:39 UTC, wysohn commented
> looks like we have to use it without fixing these things for this moment. Let's push it on development, and fix the issues later when I can finally use keyboard (´ー｀)

Sounds good! I will push it to 3.3.x

2021-07-11 11:57 UTC, rkdrns4747 commented on core/src/main/java/io/github/wysohn/triggerreactor/core/manager/trigger/command/ITabCompleter.java
> +        public static TabCompleterBuilder self(){
how 'bout instance() ? I have no idea which word I should use.

2021-07-27 01:50 UTC, rkdrns4747 commented on core/src/main/java/io/github/wysohn/triggerreactor/core/manager/trigger/command/ITabCompleter.java
> +        public static TabCompleterBuilder self(){
@wysohn bump.

2021-11-20 07:04 UTC, rkdrns4747 commented on core/src/main/java/io/github/wysohn/triggerreactor/core/manager/trigger/command/ITabCompleter.java
> +        public static TabCompleterBuilder self(){
Or, how about just removing instance() method, and just using Builder.of()? I think this way is more ideal way.

2021-11-20 20:15 UTC, wysohn commented on core/src/main/java/io/github/wysohn/triggerreactor/core/manager/trigger/command/ITabCompleter.java
> +        public static TabCompleterBuilder self(){
I think that should do it too

Sorry for some reason I didn't see your comment back then.

2021-11-20 23:22 UTC, rkdrns4747 commented on core/src/main/java/io/github/wysohn/triggerreactor/core/manager/trigger/command/ITabCompleter.java
> +        public static TabCompleterBuilder self(){
Nah, It's alright, I've been offline like almost 5 month. 😅

2021-11-21 19:51 UTC, wysohn commented
Looking good

I will do the detailed review soon, but school is kinda busy

So please bear with me will be back to it soon

2021-11-22 04:36 UTC, rkdrns4747 commented
> Looking good, thanks a lot!
> 
> I will do the detailed review soon, but school is kinda busy
> 
> So please bear with me will be back to it soon

aight. Then I'll start to work on NameSpace Feature.

2021-12-17 07:52 UTC, wysohn approved these changes
Tested it in-game and seems to be working great. Thank you!

Please go ahead and merge.

2021-12-17 20:18 UTC, merged