Added assignment, bitwise, and bit shift operator
TriggerReactor/TriggerReactor pull request #396
Opened 2021-05-05 16:54 UTC by Kuiprux

I think I messed up the commit list. Sorry for that.

2021-05-05 21:19 UTC, wysohn commented
Can you also possibly write some unit testing codes?

Tests that are just enough to cover the new implementations; it doesn't have to be super complex.

Refer to https://www.guru99.com/white-box-testing.html if you are not familiar with white-box testing.

2021-05-05 21:20 UTC, wysohn commented
examples here: https://github.com/TriggerReactor/TriggerReactor/tree/master/core/src/test/java/io/github/wysohn/triggerreactor/core/script

2021-05-06 04:09 UTC, gerzytet approved these changes
To be honest, I'm not certain why I'm still on the reviewers list after all this time.
My concern isn't the code.  Unless you do something truly deplorable, there aren't many ways to make Interpreter.java worse than it already is.  It even looks like you've cleaned part of it up.
I'm just concerned that advanced features like bitwise operators aren't useful for TriggerReactor's community of beginners.  It can't hurt, but I'm afraid almost no-one will use it.

2021-05-06 04:22 UTC, gerzytet commented
Wait, I glossed over the "assignment operators" part.  That's been a requested feature for a while.  Thanks for finally implementing it!

2021-05-06 11:35 UTC, Kuiprux commented
I agree with you. I will focus more on the essential functions.
Thank you for your opinion!

2021-05-06 18:24 UTC, wysohn requested changes
Wow thank you for the amazing work!

As gerzytet said, you are making great impacts

Can you please also cover those parts whenever gets the chance?

2021-05-06 18:24 UTC, wysohn commented on core/src/main/java/io/github/wysohn/triggerreactor/core/script/interpreter/Interpreter.java
> +                } else if ("&".equals(tokenValue) || "^".equals(tokenValue) || "|".equals(tokenValue)) {
I think from here to line 683 isn't covered by the test

2021-05-07 02:35 UTC, wysohn approved these changes

2021-05-07 02:35 UTC, merged