Executors and Placeholders Refactoring
TriggerReactor/TriggerReactor pull request #486
Opened 2022-05-30 12:32 UTC by Ioloolo

2022-05-30 13:09 UTC, Sayakie reviewed
Can you reflect these missing license headers?

2022-05-30 13:09 UTC, Sayakie commented on bukkit/src/main/resources/Executor/ACTIONBAR.js
> - *******************************************************************************/
License header for each files represent authors credit. Should restore those.

2022-05-30 13:09 UTC, Sayakie commented on bukkit/src/main/resources/Executor/BROADCAST.js
> - *******************************************************************************/
*ditto*

2022-05-30 13:09 UTC, Sayakie commented on bukkit/src/main/resources/Executor/BURN.js
> - *******************************************************************************/
*ditto*

2022-05-30 13:09 UTC, Sayakie commented on bukkit/src/main/resources/Executor/CLEARCHAT.js
> - *******************************************************************************/
And all rest missing deleted license headers should be restored.

2022-05-30 13:22 UTC, Ioloolo commented
> Can you reflect these missing license headers?

Oh.. I missed it.
btw I need to write a new code...

2022-06-12 21:15 UTC, wysohn commented
@Ioloolo 
Don't be shy to add yourself as the author to whichever file you contributed

If you have entered even just one character, you have the ownership (but I hardly can imagine that would be merged xD)

2022-07-03 10:02 UTC, Ioloolo commented
sry.. missed

2022-09-18 07:09 UTC, wysohn commented
Any update on this?

It would be awesome to include it in our next release

2022-09-18 07:14 UTC, Ioloolo commented
> Any update on this?
> 
> It would be awesome to include it in our next release

I don't have much time for this pr because of my studies.
As far as I know, only one executor needs refactoring.

I will have some free time later in October.
So I need to find someone to finish this pr instead of me.

2022-09-18 07:43 UTC, wysohn commented
> > Any update on this?
> > It would be awesome to include it in our next release
> 
> I don't have much time for this pr because of my studies. As far as I know, only one executor needs refactoring.
> 
> I will have some free time later in October. So I need to find someone to finish this pr instead of me.

No need to rush

Take your time and focus on studies

Just asking cause we will have to schedule releases

2022-10-07 17:05 UTC, Sayakie requested changes

2022-10-07 17:05 UTC, Sayakie commented on bukkit/src/main/resources/Executor/SETITEMNAME.js
> +    throw new Error('Item is null or air.');
```suggestion
  if (item.getType() === Material.AIR) {
    throw new Error('Item cannot be an AIR.');
  }
```

2022-10-07 17:05 UTC, Sayakie commented on bukkit/src/main/resources/Executor/SETTYPE.js
> +    throw new Error('Item is null or air.');
```suggestion
  if (item.getType() === Material.AIR) {
    throw new Error('Item cannot be an AIR.');
  }
```

2022-10-07 17:05 UTC, Sayakie commented on bukkit/src/main/resources/Executor/SETTYPE.js
> +  var material = Material.valueOf(type.toUpperCase());
```suggestion
  var material = Material.getMaterial(type.toUpperCase());
```

2022-10-07 17:08 UTC, Sayakie commented
너무 많은 변경점이 있어 몇몇 실행자는 아직 리뷰가 덜 끝났습니다.

해당 PR에서 스펀지의 실행자, 자리표시가와 버킷의 실행자까지만 리팩토링 진행 후 새 PR에서 버킷의 자리표시자 리팩토링을 시작하는게 어떨까요?

cc @wysohn

2022-10-08 03:25 UTC, Ioloolo commented on bukkit/src/main/resources/Executor/BROADCAST.js
> +  overloads: [[{type: 'string', name: 'message'}]],
I think so too.

2022-10-08 04:43 UTC, Ioloolo commented
저도 한번 나누는게 낫다고 생각합니다.

2022-10-11 11:27 UTC, Sayakie commented
Feel free to ping me when requested changes once be done. I would re-review changed things.

Note: Review available after next week as my exams should be end.

2022-10-11 11:31 UTC, Ioloolo commented
I haven't requested a re-review yet because I haven't changed all comment.

I'm planning to re-review as soon as possible.
but I'm not sure about my schedul.

2022-10-11 11:32 UTC, Ioloolo commented
In addition, Can you tell me what means sync argument in CMD.js?

2022-10-11 11:36 UTC, Sayakie commented
> I'm planning to re-review as soon as possible.
> but I'm not sure about my schedul.

As wysohn said, no need to rush. Focus your schedule first :)

2022-10-11 11:40 UTC, Sayakie commented
> In addition, Can you tell me what means sync argument in CMD.js?

See [Executor wiki](https://github.com/TriggerReactor/TriggerReactor/wiki/Executors_kr#cmd-cmd-spawn) for further information. Executor `CMD` consumes first argument as run as server thread (synchronously) if is equivalent to "true".

2022-10-11 11:49 UTC, Sayakie commented
**Side note**: Should be update Executors wiki. `CMD` would be expected first parameter as boolean type, but there is no context what performs do thing.

cc @rkdrns4747

2022-10-12 09:30 UTC, Sayakie commented
> In addition, Can you tell me what means sync argument in CMD.js?

Nevermind about that. It just was an outdated argument.

2022-10-15 00:01 UTC, wysohn commented
> 너무 많은 변경점이 있어 몇몇 실행자는 아직 리뷰가 덜 끝났습니다.
> 
> 해당 PR에서 스펀지의 실행자, 자리표시가와 버킷의 실행자까지만 리팩토링 진행 후 새 PR에서 버킷의 자리표시자 리팩토링을 시작하는게 어떨까요?
> 
> cc @wysohn
@Sayakie 
@Ioloolo 
인터뷰 준비하느라 바빠서 확인이 늦었네요 죄송합니다

음 상관은 없다고 생각하지만 스펀지 API 7 의 경우 3.3.x 부터는 지원이 끊기는지라 나누게된다면 버킷을 먼저 넣는게 맞지 않을까요?

나누게된다면 스펀지쪽 executor랑 placeholder는 3.4나 3.5에서 스펀지 API 8 을 지원할때 다시 확인해보는게 좋을거같습니다

2022-10-17 14:31 UTC, Sayakie requested changes
The review is not done yet. Will watch it again tomorrow.

2022-10-17 14:31 UTC, Sayakie commented on bukkit/src/main/resources/Placeholder/lore.js
> +  lore = lore.substring(0, lore.length-1);
```suggestion
  var lore = JavaString.join('\n', lores);
```

2022-10-17 14:31 UTC, Sayakie commented on bukkit/src/main/resources/Placeholder/prefix.js
> +    throw new Error('This server doesn\'t has vault.')
```suggestion
    throw new Error('Server has no Value plugin.')
```

2022-10-17 14:31 UTC, Sayakie commented on bukkit/src/main/resources/Placeholder/suffix.js
> +    throw new Error('This server doesn\'t has vault.')
```suggestion
    throw new Error('Server has no Value plugin.')
```

2022-11-14 07:15 UTC, Sayakie commented
Big sorry for late reply. Looks good to me, and seems there is no errorprone syntax. We have to testing whole of placeholders and executors on latest and legacy game server both.

+ Need rebase.

2022-11-14 07:22 UTC, Sayakie approved these changes

2022-12-12 01:48 UTC, Ioloolo commented
My schedule is all over.
I will test the in-game environment about next week

2023-01-15 21:37 UTC, wysohn approved these changes
Thank you for the hard works!

These are a lot of changes, so I think the best option to test it for now is do so in the dev branch.

Lets see how it goes

2023-01-15 21:40 UTC, merged