fix: No JavaScript engine available on Paper
TriggerReactor/TriggerReactor pull request #544
Opened 2023-03-10 05:58 UTC by Sayakie

By default with no parameters, ScriptEngineManager automatically bound with ClassLoader of current thread that would maybe affect as some conflict against Spigot folks like paper.

Pass `null` whilst ScriptEngineManager is constructing to fix the above facing issue. The pull request also fixes #543 and so on fixes #530 maybe.

2023-03-10 06:00 UTC, Sayakie commented
Heres an pre-built jars: [TriggerReactor-bukkit-3.3.5.1-Beta.zip](https://github.com/TriggerReactor/TriggerReactor/files/10939061/TriggerReactor-bukkit-3.3.5.1-Beta.zip)

I'm tested with **`paper-1.19.3-445`**.

2023-03-10 06:13 UTC, Sayakie commented
Tested with also **`Paper-1.19.3-431`**, looks everything works healthy.

![image](https://user-images.githubusercontent.com/18323202/224237705-07cd19ca-dd40-41fe-8125-33586f1b4de1.png)

2023-03-10 19:00 UTC, wysohn commented
This is awesome, Thank you!

Though, I looked into the documentation here: https://docs.oracle.com/javase/7/docs/api/javax/script/ScriptEngineManager.html#ScriptEngineManager(java.lang.ClassLoader)

providing `null` means using the script engine factory that is bundled to the java itself, and I believe it didn't work in some occasion though I wasn't really sure about the reason behind it. It might be happend in Sponge, but since we no longer have the support, I can't really confirm it. So knowing 'why' it happened would be a great question to ask.

Also, should we delete this line of code? https://github.com/TriggerReactor/TriggerReactor/blob/23fcc893a5f2af269069ed20a27dba642fbfb711/bukkit/src/main/java/io/github/wysohn/triggerreactor/bukkit/main/BukkitTriggerReactorCore.java#L226

As someone reported, having TriggerReactor enabled prevent other plugins from loading the script engines, so I definitely think it's something to do with the context class loader. Cause most likely a single thread is used when loading all the plugin jars, so overriding the existing classloader might caused the problem.

Might be worthwhile to investigate a bit more into craftbukkit to see how the custom classloader works

2023-03-11 05:52 UTC, Sayakie commented
> So knowing 'why' it happened would be a great question to ask.

Yeah, it's important things to know, but I really can't point out what happens in backstage. I just assume there are some 'conflicts' between Bukkit plugin classloader and Java service provider.

> Also, should we delete this line of code? https://github.com/TriggerReactor/TriggerReactor/blob/23fcc893a5f2af269069ed20a27dba642fbfb711/bukkit/src/main/java/io/github/wysohn/triggerreactor/bukkit/main/BukkitTriggerReactorCore.java#L226

Unfortunately we can't. I confirmed same issue messaged "No JavaScript engine available".

2023-03-11 05:55 UTC, Sayakie commented
Rebase

2023-03-12 04:53 UTC, wysohn commented
> > So knowing 'why' it happened would be a great question to ask.
> 
> Yeah, it's important things to know, but I really can't point out what happens in backstage. I just assume there are some 'conflicts' between Bukkit plugin classloader and Java service provider.
> 
> > Also, should we delete this line of code? https://github.com/TriggerReactor/TriggerReactor/blob/23fcc893a5f2af269069ed20a27dba642fbfb711/bukkit/src/main/java/io/github/wysohn/triggerreactor/bukkit/main/BukkitTriggerReactorCore.java#L226
> 
> Unfortunately we can't. I confirmed same issue messaged "No JavaScript engine available".

That's very confusing indeed

I'm concerned about the report that using TriggerReactor prevents other plugins from loading the JavaScript engines, so I think changing the context class loader has something to do with that.

My wild guess is that since a single thread is visiting every plugins in turn and call `onEnable()` on them, so once TriggerReactor use the `setContextClassLoader,` we may have changed something so other plugins, which are enabled later than TriggerReactor, can't no longer locate the JavaScript engines

Did this also be fixed by any chance?

2023-03-13 07:21 UTC, Sayakie commented
> .. using TriggerReactor prevents other plugins from loading the JavaScript engines, so I think changing the context class loader has something to do with that.
> 
> Did this also be fixed by any chance?

Let's reproduce step by step then see the result. I assume one of our member can confirm the edge cases.

cc @LimuLhw

2023-03-25 22:09 UTC, wysohn commented
I've checked the discord log to see what exactly the plugin that was conflicting with TRG but no luck

The reporter simply stated there was a conflict, and it was 6 months ago

Lets just merge it for now. I've also checked that at least it works for spigot and paper.

2023-03-25 22:11 UTC, wysohn requested changes
Can we rebase this to be forked from main, not development?

We will need this to be effective immediately without going through the dev branch

2023-05-01 12:30 UTC, Sayakie commented
First of all, big sorry for the delayed reply. I'm so busy due to activities at the school.

> Can we rebase this to be forked from main, not development?

I think rebasing commits with this PR flow is horrible, so what about closing the PR and creating a new one from the master branch?

2023-05-08 03:47 UTC, wysohn commented
> First of all, big sorry for the delayed reply. I'm so busy due to activities at the school.
> 
> > Can we rebase this to be forked from main, not development?
> 
> I think rebasing commits with this PR flow is horrible, so what about closing the PR and creating a new one from the master branch?

Sure! Whichever works the best for you

I've done it using cherry pick last time with new branch too

2023-05-08 04:15 UTC, Sayakie commented
See #550

2023-05-08 04:15 UTC, closed without merging