feat: Elvis 연산자 및 Optional Chaining 연산자 추가
TriggerReactor/TriggerReactor pull request #611
Opened 2023-09-29 04:14 UTC by Sayakie

이 PR은 Elvis 연산자(`?:`)와 Optional Chaining 연산자(`?.`)를 추가합니다.

## Elvis Operator (엘비스 연산자)
엘비스 연산자(`?:` 연산자)는 코틀린 문법에서 영감을 받았습니다. 왼쪽 피연산자가 `null`일 때 오른쪽 피연산자를 반환하고, 그렇지 않다면 왼쪽 피연산자를 반환하는 논리 연산자입니다.

### 문법
```kt
leftExpr ?: rightExpr
```

### 예제
```kt
thePlayer = Bukkit.getServer().getPlayer(args[0]) ?: player
```

## Optional Chaining Operator (옵셔널 체이닝 연산자)
옵셔널 체이닝 연산자(`?.` 연산자)는 자바스크립트 생태계에서 널리 쓰이는 문법 중 하나입니다. 각 객체의 참조를 확인하는 `.` 연산자와 비슷하지만 참조가 `null`일 때 에러를 발생시키는 대신에 표현식의 결과값으로 `null`을 반환합니다.

### 문법
```kt
instance?.field
array?.[index]
method?.(args)

instance?.field?.method?.(args)?.field?.array?.[index]
```

### 예제
```kt
somePlugin = plugin("SomePlugin")
somePlugin?.getBossManager?.()?.generateNew?.(UUID.randomUUID())?.hp?.[0]
```

2023-09-30 22:42 UTC, wysohn requested changes
감사합니다! 코드 정리까지 해주셔서 더 보기 좋네요

한가지만 덧붙이자면 best practice를 위해서 PR하나에는 하나의 주제만 담겨 있으면 좋을거같아요

Elvis 하나, Optional Chaining 하나, 가능하면 코드 정리도 따로 PR하나로!

다만 이번거는 다시 정리하기 어려울거같기도 하고 딱히 겹치는 부분은 없을거같으니 그냥 넘어가는걸로 해요!

2023-09-30 22:42 UTC, wysohn commented on core/src/main/java/io/github/wysohn/triggerreactor/core/script/interpreter/Interpreter.java
> +    private int safeAccessStack = 0;
Interpreter 하나를 여러 Trigger가 동시에 사용하기때문에 race-condition이 생길 가능성이 있습니다

InterpreterLocalContext로 옮겨주세요!

2023-09-30 23:10 UTC, wysohn commented
@Sayakie 
그 아직 코드만 봐가지고는 확실히 이해가 안가서 그런데 Whitespace를 skip 안하고 따로 토큰화 시킨 이유가 있나요? 뭔가 문제가 있어서 그랬던건 알겠는데 그냥 눈대중으로는 잘 모르겠네요

2023-09-30 23:20 UTC, Sayakie commented
> 감사합니다! 코드 정리까지 해주셔서 더 보기 좋네요
> 
> 한가지만 덧붙이자면 best practice를 위해서 PR하나에는 하나의 주제만 담겨 있으면 좋을거같아요
> 
> Elvis 하나, Optional Chaining 하나, 가능하면 코드 정리도 따로 PR하나로!
> 
> 다만 이번거는 다시 정리하기 어려울거같기도 하고 딱히 겹치는 부분은 없을거같으니 그냥 넘어가는걸로 해요!

Elvis와 Optional Chaining은 서로 상호보완하는 연산자라고 생각해서 같은 PR에 있는 게 좋다고 생각했어요. 단, 코드 정리(`parseIf`, `parseWhile`)와 같은 경우 다른 PR에서 했던게 좋았을지도 모르겠네요.

다음에는 좀 더 고려해서 PR 만들도록 하겠습니다. 감사합니다.

2023-09-30 23:21 UTC, Sayakie commented on core/src/main/java/io/github/wysohn/triggerreactor/core/script/interpreter/Interpreter.java
> +    private int safeAccessStack = 0;
아, 그렇겠네요. 수정하겠습니다!

2023-09-30 23:29 UTC, wysohn commented on Production_Code.bnf
> +                     | <term> '?:' <expression>
그 Elvis 가 expression으로 생각되는게 맞을까요? 저도 확실하진 않은데 보통 id랑 같이 가지 않나요? null이 될수 있는 경우를 테스트하는거라 최대한 넓게봐도 factor에 들어가는게 맞을거같긴한데 어떻게 생각하시나요?

예를들어 `1+4/2 :? 55` 이런 문법이 가능하다는건데 expression에서 null이 나올 수가 있는지 모르겠어요

2023-09-30 23:35 UTC, Sayakie commented
> 그 아직 코드만 봐가지고는 확실히 이해가 안가서 그런데 Whitespace를 skip 안하고 따로 토큰화 시킨 이유가 있나요? 뭔가 문제가 있어서 그랬던건 알겠는데 그냥 눈대중으로는 잘 모르겠네요

Parser가 토큰을 스킵할 지 여부를 결정해주기 위함입니다. PR에서 `parseId` 메소드의 일부 동작이 달라졌는데 가장 크게 볼 부분은 여깁니다:
https://github.com/TriggerReactor/TriggerReactor/blob/d019a7ae37c198d12b92ed0c353063e775d3a6dc/core/src/main/java/io/github/wysohn/triggerreactor/core/script/parser/Parser.java#L1451-L1455

`.`만 인식하지 않고 토큰이 ID이거나 `[`, `(`, `@` 중 하나로 시작할 때에도 반복되게 설계됐는데, 만약 Whitespace를 토큰화하지 않고 그대로 사용하면 아래 예시 코드에서 문제가 발생합니다.
```kt
SWITCH <factor>
  CASE <logic> => <statement>
(이하 생략)
```
Switch statement에서는 평가될 식(`<factor>`) 다음에 CASE statement가 오게 됩니다. 만약 Whitespace를 토큰화하지 않는다면 파서가 CASE까지 ID로 인식하여 문제가 발생합니다.

2023-09-30 23:43 UTC, wysohn commented
> > 그 아직 코드만 봐가지고는 확실히 이해가 안가서 그런데 Whitespace를 skip 안하고 따로 토큰화 시킨 이유가 있나요? 뭔가 문제가 있어서 그랬던건 알겠는데 그냥 눈대중으로는 잘 모르겠네요
> 
> Parser가 토큰을 스킵할 지 여부를 결정해주기 위함입니다. PR에서 `parseId` 메소드의 일부 동작이 달라졌는데 가장 크게 볼 부분은 여깁니다:
> 
> https://github.com/TriggerReactor/TriggerReactor/blob/d019a7ae37c198d12b92ed0c353063e775d3a6dc/core/src/main/java/io/github/wysohn/triggerreactor/core/script/parser/Parser.java#L1451-L1455
> 
> `.`만 인식하지 않고 토큰이 ID이거나 `[`, `(`, `@` 중 하나로 시작할 때에도 반복되게 설계됐는데, 만약 Whitespace를 토큰화하지 않고 그대로 사용하면 아래 예시 코드에서 문제가 발생합니다.
> 
> ```kotlin
> SWITCH <factor>
>   CASE <logic> => <statement>
> (이하 생략)
> ```
> 
> Switch statement에서는 평가될 식(`<factor>`) 다음에 CASE statement가 오게 됩니다. 만약 Whitespace를 토큰화하지 않는다면 파서가 CASE까지 ID로 인식하여 문제가 발생합니다.

아 감사합니다

사실 이거는 2017년의 제가 일종의 야메로 만든 코드에 가까워서 생기는 문제인거같은데

음 깔끔하게 하려면 parseId를 다시 설계하는게 좋을거같긴한데 어떻게 생각하시나요?

whitespace를 굳이 토큰으로 해야 하는 이유는 이 설계미스로 인한거로 생각되네요. 

이미 작성도 다 하고 테스트도 되었으니 이대로 가도 되지만 마지막으로 한번 생각해보심이 ㅋㅋ.. 2017년의 저를 대신해서 사과드립니다

지금 안하면 미래의 누군가가 고통받을것이고 지금 한다면 사야키님이 고통받을것인데 아마 미래에 하는것보다는 덜하긴 할거에요

2023-09-30 23:59 UTC, Sayakie commented
> 아 감사합니다
> 
> 사실 이거는 2017년의 제가 일종의 야메로 만든 코드에 가까워서 생기는 문제인거같은데
> 
> 음 깔끔하게 하려면 parseId를 다시 설계하는게 좋을거같긴한데 어떻게 생각하시나요?
> 
> whitespace를 굳이 토큰으로 해야 하는 이유는 이 설계미스로 인한거로 생각되네요.
> 
> 이미 작성도 다 하고 테스트도 되었으니 이대로 가도 되지만 마지막으로 한번 생각해보심이 ㅋㅋ.. 2017년의 저를 대신해서 사과드립니다
> 
> 지금 안하면 미래의 누군가가 고통받을것이고 지금 한다면 사야키님이 고통받을것인데 아마 미래에 하는것보다는 덜하긴 할거에요

음, 저는 지금도 `parseId`를 재설계했다고 생각합니다. 현재 트리거리액터는 여러 개의 메소드 체이닝이나 배열 접근을 할 수 없었는데, 이 PR에선 파서가 ***적어도 에러는 내지 않습니다.***
```kt
methodChaining()[4]()?.()?.[127]?.()
```
와 같이 사용할 수 있고, 아래와 같은 노드 트리구조가 만들어집니다.
```
[type: ROOT, value: '<ROOT>'] at row[-1], col[-1]
  [type: OPERATOR, value: '?.'] at row[1], col[16]
    [type: OPERATOR, value: '?.'] at row[1], col[16]
      [type: OPERATOR, value: '?.'] at row[1], col[16]
        [type: OPERATOR, value: '.'] at row[1], col[16]
          [type: OPERATOR, value: '.'] at row[1], col[16]
            [type: OPERATOR, value: '.'] at row[1], col[16]
              [type: THIS, value: '<This>'] at row[1], col[16]
              [type: CALL, value: 'methodChaining'] at row[1], col[16]
            [type: ARRAYACCESS, value: '<Array Access>'] at row[1], col[16]
              [type: ID, value: 'methodChaining'] at row[1], col[16]
              [type: INTEGER, value: '4'] at row[1], col[20]
          [type: CALL, value: 'methodChaining'] at row[1], col[16]
        [type: CALL, value: 'methodChaining'] at row[1], col[16]
      [type: ARRAYACCESS, value: '<Array Access>'] at row[1], col[16]
        [type: ID, value: 'methodChaining'] at row[1], col[16]
        [type: INTEGER, value: '127'] at row[1], col[33]
    [type: CALL, value: 'methodChaining'] at row[1], col[16]
```

Interpreter에선 아직 작동이 되지 않지만 그건 미래의 즐거움으로 남겨두고, 이번엔 코드 개선에 의의를 두었습니다.

2023-10-01 00:02 UTC, Sayakie commented on Production_Code.bnf
> +                     | <term> '?:' <expression>
이거는 제가 맨 처음 PR 주제를 잡을 때 여기가 적당하겠다고 생각하고 깜빡해서(..) 생긴 문제 같습니다. 저도 factor에 들어가는게 맞는 것 같아요.

2023-10-07 23:46 UTC, wysohn commented on Production_Code.bnf
> +                     | <term> '?:' <expression>
이거는 그럼 해결이 된거라고 보면 될까요?

2023-10-08 01:47 UTC, Sayakie commented
## 체이닝 지원 추가 🚀

이제 여러 accessors들을 연결해서 사용할 수 있습니다.
다음 코드도 정상 작동해요!
```kt
a.b.c.d.e.methodChaining(a, 3 + b * 4)[4]?.h()?.[127]
arrayOf(10, 20, 30, 40, 50)?.[4]
arrayOf(10, 20, 30)?.[100] ?: "몰?루"
```

## Elvis operator 순서 조정

엘비스 연산자의 순서를 조정해 이제 `leftExpr`에서 **null**이 올 수 없는 상황에서는 사용할 수 없습니다: `1 + 2 / 4 ?: -1`

2023-10-08 05:21 UTC, wysohn commented on Production_Code.bnf
> +                     |  '{' <logic> '}'
이거는 <logic> 으로 바꾸는게 맞을까요? key는 항상 String인게 맞긴한데 

하기는 받은값을 toString()만 해줘도 되기는 하죠

문법으로 아예 막아버릴지 toString()으로 해결할지 결정해야 할 사안이겠네요 어찌 생각하시나요

2023-10-08 05:31 UTC, Sayakie commented on Production_Code.bnf
> +                     |  '{' <logic> '}'
이거는 파서에서 logic으로 값을 가져오고 있어서 그에 맞추어 수정했습니다. 사실 bnf 파일의 정확한 용도는 모르겠네요..

2023-10-08 07:23 UTC, wysohn commented on Production_Code.bnf
> +                     |  '{' <logic> '}'
> 이거는 파서에서 logic으로 값을 가져오고 있어서 그에 맞추어 수정했습니다. 사실 bnf 파일의 정확한 용도는 모르겠네요..

앞으로는  bnf로 문법을 맞춘다음에 코드를 짜려구요

지금까지는 그냥 생각나는대로 막 한거라 저번에 bitter 재정의 할때는 도움이 많이 되더라구요

둘이 맞지 않는 부분이 있으면 사실 코드를 거기에 맞춰서 가는게 맞긴 한데 bnf 자체도 급조한거라 좀 안맞는게 있을수도 있어요 경중을 따지자면 bnf를 정확하게 하는게 맞다고 저는 생각해요

2023-10-08 10:45 UTC, Sayakie commented on Production_Code.bnf
> +                     |  '{' <logic> '}'
아하 그렇군요. 혹시 bnf 파일을 검증할 수 있는 방법이 있을까요? 구글링을 조금 해보았지만 관련 레퍼런스가 많이 적네요.

현재 트리거리액터는 아래 예시 같이 문자열을 조합할 수 있도록 구현되어 있기 때문에 `<logic>`이 맞다고 생각해요.
```kt
{"v1" + "." + player.getUniqueId() + "." + "stack"} = stack++
```

2023-10-08 22:42 UTC, wysohn commented on Production_Code.bnf
> +                     |  '{' <logic> '}'
> 아하 그렇군요. 혹시 bnf 파일을 검증할 수 있는 방법이 있을까요? 구글링을 조금 해보았지만 관련 레퍼런스가 많이 적네요.
> 
> 현재 트리거리액터는 아래 예시 같이 문자열을 조합할 수 있도록 구현되어 있기 때문에 `<logic>`이 맞다고 생각하는데, 어떻게 생각하시나요?
> 
> ```kotlin
> {"v1" + "." + player.getUniqueId() + "." + "stack"} = stack++
> ```

가장 최선의 검증방법은 이전에 하던대로 AST트리 확인하는게 가장 좋은거같아요 post-order 로 실행했을때 bnf에 정의된대로 실행이 되기만 하면 되니까요 .예를들어 Assignment ('=') 노드가 있으면 children에 노드가 logic에 2개 들어가야 할거고 만약에 아니면 그 아래의 <logic> 으로 치환이 되겠죠

그렇네요! 좀더 조이자면 <expression> 이 맞을거같긴하네요 키로 comparison이나 그 위를 쓰는 경우는 없을거 같기는 한데 뭔가 제가 놓친게 있을까요?

2023-10-08 23:58 UTC, Sayakie commented on Production_Code.bnf
> +                     |  '{' <logic> '}'
> 가장 최선의 검증방법은 이전에 하던대로 AST트리 확인하는게 가장 좋은거같아요 post-order 로 실행했을때 bnf에 정의된대로 실행이 되기만 하면 되니까요 .예를들어 Assignment ('=') 노드가 있으면 children에 노드가 logic에 2개 들어가야 할거고 만약에 아니면 그 아래의 으로 치환이 되겠죠

아하 알겠습니다.

> 그렇네요! 좀더 조이자면 이 맞을거같긴하네요 키로 comparison이나 그 위를 쓰는 경우는 없을거 같기는 한데 뭔가 제가 놓친게 있을까요?

저도 키 값으로 `<expression>`이 적절해 보이네요. PR에 적용할까요?

2023-10-09 00:04 UTC, wysohn commented on Production_Code.bnf
> +                     |  '{' <logic> '}'
> > 가장 최선의 검증방법은 이전에 하던대로 AST트리 확인하는게 가장 좋은거같아요 post-order 로 실행했을때 bnf에 정의된대로 실행이 되기만 하면 되니까요 .예를들어 Assignment ('=') 노드가 있으면 children에 노드가 logic에 2개 들어가야 할거고 만약에 아니면 그 아래의 으로 치환이 되겠죠
> 
> 아하 알겠습니다.
> 
> > 그렇네요! 좀더 조이자면 이 맞을거같긴하네요 키로 comparison이나 그 위를 쓰는 경우는 없을거 같기는 한데 뭔가 제가 놓친게 있을까요?
> 
> 저도 키 값으로 `<expression>`이 적절해 보이네요. PR에 적용할까요?

네넵

2023-10-15 04:03 UTC, wysohn approved these changes

2023-10-15 05:11 UTC, merged